export const GET_TICKET_CARDS = "GET_TICKET_CARDS";
export const SET_LOADING_PENDING = "SET_LOADING_PENDING";
export const SET_LOADING_SUCCESS = "SET_LOADING_SUCCESS";
export const SOMETHING_ERROR = "SOMETHING_ERROR";